---
- name: "Configure StreamAlert files"
  hosts: localhost
  vars_files:
    - defaults.yml
    - global_conf_vars.yaml
  vars_prompt:
    - name: account_id
      prompt: "Enter AWS Account ID:"
      private: no

  tasks:
    - name: Clone StreamAlert Repo
      git:
        dest: "{{ playbook_dir }}/streamalert"
        repo: https://github.com/airbnb/streamalert.git
        version: stable
        force: no
        update: no
      tags:
        - clone

    - name: Rule Creation Block
      tags:
        - rules
      block:
        - name: Ensure rhythmic rules dir exists
          file:
            path: "{{ playbook_dir }}/streamalert/rules/rhythmic"
            state: directory
        - name: Ensure __init__.py exists in rules dir
          file:
            path: "{{ playbook_dir }}/streamalert/rules/rhythmic/__init__.py"
            state: touch
        - name: Ensure rules have been templated
          template:
            src: "{{ item }}"
            dest: "{{ playbook_dir }}/streamalert/rules/rhythmic/{{ item | basename | regex_replace('.j2','') }}"
          with_fileglob:
            - templates/rules/*.j2

    - name: Config Block
      tags:
        - config
      block:
        - name: Load config from file
          include_vars:
            file: streamalert/conf/global.json
            name: streamalert_global_imported

        - name: Set vars
          set_fact:
            streamalert_global_mods:
              general:
                rule_locations:
                  - rules/rhythmic
              account:
                aws_account_id: "{{ aws_account_id | quote}}"

        - name: Modify json
          set_fact:
            streamalert_global_result: "{{ streamalert_global_imported | combine(streamalert_global_mods, recursive=True) }}"

        - name: Ensure conf file is written
          copy:
            content: "{{ streamalert_global_result | to_nice_json(indent=2) }}"
            dest: "{{ playbook_dir }}/streamalert/conf/global.json"

    - name: Virtualenv Block
      tags:
        - dependencies
        - pip
        - virtualenv
      block:
        - name: Ensure Python requirements are installed
          pip:
            requirements: "{{ playbook_dir }}/streamalert/requirements.txt"
            virtualenv: "{{ venv }}"
            virtualenv_python: python2.7
            virtualenv_site_packages: yes
        - name: Ensure venv wrapper is present
          template:
            src: templates/venv_exec.j2
            dest: "{{ venv }}/exec"
            mode: "755"

    - name: Ensure Input SNS Topic is Created
      tags:
      - buckets
      vars:
        ansible_python_interpreter: "{{ playbook_dir }}/venv/exec"
      vars_prompt:
      - name: sns_input_topic_name
        prompt: "Insert SNS Topic Name"
        private: no
      sns_topic:
        name: "{{ sns_input_topic_name }}"
        region: "{{ region }}"

    - name: Input Configuration
      tags:
        - input
      block:
      - name: Load prod.json file
        include_vars: 
         file: streamalert/conf/clusters/prod.json
         name: streamalert_prod_imported
      - name: Set vars
        set_fact:
          streamalert_prod_mods:
            inputs:
              - "arn:aws:sns:{{ region }}:{{ aws_account_id }}:{{ sns_input_topic_name }}"
      - name: Modify json
        set_fact:
          streamalert_prod_result: "{{ streamalert_prod_imported | combine(streamalert_prod_mods, recursive=True) }}"
      - name: Ensure conf file is written
        copy:
          content: "{{ streamalert_prod_result | to_nice_json(indent=2) }}"
          dest: ./streamalert/conf/prod.json      

      - name: Load sources.json
        include_vars: 
         file: streamalert/conf/sources.json
         name: streamalert_sources_imported
      - name: Set vars
        vars: 
          - topic: "{{ sns_input_topic_name }}"
        set_fact:
          streamalert_sources_mods:
            sns:
              topic:
                logs:
                - "cloudwatch"
      - name: Modify json
        set_fact:
          streamalert_sources_result: "{{ streamalert_sources_imported | combine(streamalert_sources_mods, recursive=True) }}"    
      - name: Ensure conf file is written
        copy:
          content: "{{ streamalert_sources_result | to_nice_json(indent=2) }}"
          dest: ./streamalert/conf/sources.json

- name: Deploy Streamalert
  hosts: localhost
  tags:
    - deploy
  vars:
    ansible_python_interpreter: "{{ playbook_dir }}/venv/exec"
  vars_prompt:
    - name: environment_name
  module_defaults:
    command:
      chdir: "{{ playbook_dir }}/streamalert"
    shell:
      chdir: "{{ playbook_dir }}/streamalert"
  tasks:
    - name: Configure bucket prefix
      command: "./manage.py configure prefix {{ environment_name }}"

    - name: initialize
      shell: yes yes | ./manage.py init
      tags:
        - init
    
- name: Configure Slack Output
  hosts: localhost
  tags:
    - out
  vars: 
    ansible_python_interpreter: "{{ playbook_dir }}/venv/exec"
  module_defaults:
    command:
      chdir: "{{ playbook_dir }}/streamalert"
    shell:
      chdir: "{{ playbook_dir }}/streamalert"
  tasks:
    - name: Use expect script to setup slack
      command: "./output.exp"
    - name: Build StreamAlert
      command: yes yes | ./manage.py build
    - name: Deploy StreamAlert
      command: yes yes | ./mangage.py deploy --function all