---
- name: "Configure StreamAlert files"
  hosts: localhost
  vars_files:
    - testVarFile.yaml
  tasks:
    - name: Clone StreamAlert Repo
      git:
        dest: ./streamalert
        repo: https://github.com/airbnb/streamalert.git
        version: stable
        force: yes
      tags:
        - clone
    - name: Ensure rhythmic rules dir exists
      file:
        path: streamalert/rules/rhythmic
        state: directory
      tags:
        - rules
    - name: Ensure __init__.py exists in rules dir
      file:
        path: streamalert/rules/rhythmic/__init__.py
        state: present
      tags:
        - rules
    - name: Ensure rules have been templated
      template:
        src: "{{ item }}"
        dest: streamalert/rules/rhythmic/{{ item | basename | regex_replace('.j2','') }}
      with_fileglob:
        - templates/rules/*.j2
      tags:
        - rules

    - name: Ensure Config is set correctly
      tags:
        - config
      block:
        - name: load config from file
          slurp:
            src: ./streamalert/conf/global.json
          register: streamalert_global_raw
        - name: Set vars
          set_fact:
            streamalert_global_imported: "{{ streamalert_global_raw.content | b64decode | from_json }}"
            streamalert_global_mods:
              general:
                rule_locations:
                  - rules/rhythmic
        - name: Modify json
          set_fact:
            streamalert_global_result: "{{ streamalert_global_imported | combine(streamalert_global_mods, recursive=True) }}"
        - name: Ensure conf file is written
          copy:
            content: "{{ streamalert_global_result | to_nice_json(indent=2) }}"
            dest: ./streamalert/conf/global.json

    - name: Ensure Python requirements are installed
      pip:
        requirements: ./streamalert/requirements.txt
        virtualenv: venv
        virtualenv_python: python2.7
      tags:
        - dependencies
        - pip
        - virtualenv

- name: Deploy Streamalert
  hosts: localhost
  vars:
    ansible_python_interpreter: venv/bin/python
  defaults:
    aws_account_id: 743955215550
    environment: test
  tasks:
    - command: "./manage.py configure aws_account_id {{ aws_account_id }}"
      args:
        chdir: streamalert
    - command: "./manage.py configure prefix {{ environment }}"
      args:
        chdir: streamalert
    - name: initialize
      shell: yes yes | ./manage.py init
      args:
        chdir: streamalert
