---
- name: "Template the Rules"
  hosts: localhost
  vars_files:
  - output.test.yaml
  
  tasks:
  - name: Clone StreamAlert Repo
    git:
      dest: ./streamalert
      repo: https://github.com/airbnb/streamalert.git
      version: stable

  - name: Ensure rules have been tepmlated
    template:
      src: "{{ item }}"
      dest: streamalert/rules/rhythmic/{{ item | basename | regex_replace('.j2','') }}
    with_fileglob:
      - streamalert.templates/*.j2

