---
- name: "Configure StreamAlert files"
  hosts: localhost
  vars_files:
    - defaults.yml
  tasks:
    - name: Clone StreamAlert Repo
      git:
        dest: "{{ playbook_dir }}/streamalert"
        repo: https://github.com/airbnb/streamalert.git
        version: stable
        force: no
        update: no
      tags:
        - clone

    - name: Rules Block
      tags:
        - rules
      block:
        - name: Ensure rhythmic rules dir exists
          file:
            path: "{{ playbook_dir }}/streamalert/rules/rhythmic"
            state: directory
        - name: Ensure __init__.py exists in rules dir
          file:
            path: "{{ playbook_dir }}/streamalert/rules/rhythmic/__init__.py"
            state: touch
        - name: Ensure rules have been templated
          template:
            src: "{{ item }}"
            dest: "{{ playbook_dir }}/streamalert/rules/rhythmic/{{ item | basename | regex_replace('.j2','') }}"
          with_fileglob:
            - templates/rules/*.j2

    - name: Config Block
      tags:
        - config
      block:
        - name: Load config from file
          include_vars:
            file: streamalert/conf/global.json
            name: streamalert_global_imported
        - name: Set vars
          set_fact:
            streamalert_global_mods:
              general:
                rule_locations:
                  - rules/rhythmic
              account:
                aws_account_id: "{{ aws_account_id | quote}}"
        - name: Modify json
          set_fact:
            streamalert_global_result: "{{ streamalert_global_imported | combine(streamalert_global_mods, recursive=True) }}"
        - name: Ensure conf file is written
          copy:
            content: "{{ streamalert_global_result | to_nice_json(indent=2) }}"
            dest: ./streamalert/conf/global.json

    - name: Virtualenv Block
      tags:
        - dependencies
        - pip
        - virtualenv
      block:
        - name: Ensure Python requirements are installed
          pip:
            requirements: "{{ playbook_dir }}/streamalert/requirements.txt"
            virtualenv: "{{ venv }}"
            virtualenv_python: python2.7
            virtualenv_site_packages: yes
        - name: Ensure venv wrapper is present
          template:
            src: templates/venv_exec.j2
            dest: "{{ venv }}/exec"
            mode: "755"

- name: Deploy Streamalert
  hosts: localhost
  tags:
    - deploy
  vars:
    ansible_python_interpreter: "{{ playbook_dir }}/venv/exec"
    environment_name: test
  module_defaults:
    command:
      chdir: "{{ playbook_dir }}/streamalert"
    shell:
      chdir: "{{ playbook_dir }}/streamalert"
  tasks:
    - name: Configure bucket prefix
      command: "./manage.py configure prefix {{ environment_name }}"
    - name: initialize
      shell: yes yes | ./manage.py init
      tags:
        - init
