- name: Ensure active rules dir exists
  file:
    path: "{{ playbook_dir }}/streamalert/rules/{{ active_rules_dir }}"
    state: directory
    
- name: Ensure __init__.py exists in rules dir
  file:
    path: "{{ playbook_dir }}/streamalert/rules/{{ active_rules_dir }}/__init__.py"
    state: touch

- name: Ensure rules have been templated
  template:
    src: "{{ item }}"
    dest: "{{ playbook_dir }}/streamalert/rules/{{ active_rules_dir }}/{{ item | basename | regex_replace('.j2','') }}"
  with_fileglob:
    - templates/rules/*.j2
    