- name: Ensure Python requirements are installed
  pip:
    requirements: "{{ playbook_dir }}/streamalert/requirements.txt"
    virtualenv: "{{ venv }}"
    virtualenv_python: python3.7
    virtualenv_site_packages: yes

- name: Ensure pexpect is in virtual environment
  pip:
    name: pexpect
    virtualenv: "{{ venv }}"
    virtualenv_python: python3.7

- name: Ensure venv wrapper is present
  template:
    src: templates/venv_exec.j2
    dest: "{{ venv }}/exec"
    mode: "755"
